# YOLO模型训练配置

# 数据配置
data_dir: "data/training"
weights_dir: "models/weights"

# 训练参数
batch_size: 16
epochs: 100
img_size: 640
workers: 8
cache: true
device: "0"  # 使用第一个GPU，多GPU用 "0,1,2,3"

# 模型配置
pretrained: "yolov5m.pt"  # 预训练权重
yolo_repo: "tools/yolov5"  # YOLOv5仓库路径

# 类别定义
classes:
  - "monster"     # 怪物
  - "boss"        # Boss
  - "door"        # 门
  - "item"        # 物品
  - "npc"         # NPC
  - "player"      # 玩家
  - "hp_bar"      # 生命条
  - "mp_bar"      # 魔法条
  - "skill_ready" # 技能就绪
  - "cooldown"    # 技能冷却

# 增强设置
augmentation:
  hsv_h: 0.015  # 色调增强
  hsv_s: 0.7    # 饱和度增强
  hsv_v: 0.4    # 亮度增强
  degrees: 0.0  # 旋转角度
  translate: 0.1 # 平移
  scale: 0.5    # 缩放
  shear: 0.0    # 剪切
  perspective: 0.0 # 透视
  flipud: 0.0   # 上下翻转
  fliplr: 0.5   # 左右翻转
  mosaic: 1.0   # 马赛克增强
  mixup: 0.0    # 混合增强